### ISSUE TITLE
custom hotkeys are not assigned correctly to upgrades

### ISSUE THREAD

**Issue by arcsaber** [w3champions/w3champions-launcher#39]
11:18 PM] MinigunSC2: [resm]
Moon
Hotkey=Q,Q,Q
works
[11:19 PM] MinigunSC2: w3champions was only putting hotkey=Q

**Comment by modmoto** [comment]
what does that mean? Buying the moonstone?

**Comment by arcsaber** [comment]
Apparently the bug happened with the 2nd bear upgrade, the 2nd archer defense upgrade, and the second bear/dryad armor upgrade, the hotkey was only set for the first upgrade of those

**Comment by modmoto** [comment]
ah ok now i get it, jeah thanks. That makes sense.

**Comment by modmoto** [comment]
fixed this in the latest beta release
