### ISSUE TITLE
extra paranoid modes for item hotkeys

### ISSUE THREAD

**Issue by arcsaber** [w3champions/w3champions-launcher#42]
- set an option to never turn hotkeys off
and/or
- set an option to play a sound each time a game starts and hotkeys are turned on

**Comment by modmoto** [comment]
i wanted to implement the button for hotkeys as floating button somehow, so you always see what is going on. Of course the option to never turn it off is also a good idea.

**Comment by arcsaber** [comment]
Floating button is much better because of the bug I described in the other issue.
