### ISSUE TITLE
Save a copy of the user's customkeys.txt when they are first loaded

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-launcher#44]
It may be a nice feature to save a copy of the user's existing customkeys.txt when the launcher boots, so that if they want to revert back to their old hotkeys, they can re-import the old ones.

**Comment by modmoto** [comment]
right now we only import the on the first time. We can make a backup of the hotkeys on the first import, maybe?

**Comment by modmoto** [comment]
closed with https://github.com/w3champions/w3champions-launcher/pull/47
