### ISSUE TITLE
Indicate which icons/abilities cannot be moved

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-launcher#45]
Some of the Warcraft 3 abilities cannot be moved around on the command card (e.g. Gargoyle Prioritize)

It would be nice if we could catalogue those abilities and label them as unmovable in the UI somehow.

**Comment by modmoto** [comment]
Do you have them? If you have the data, I can code something up. Not that hard, to be honest.

**Comment by Cepheid-UK** [comment]
You can search through customkeys.txt, if they have a "buttonpos" field, they can be moved.

At least that's what I've been reported.

**Comment by modmoto** [comment]
you mean in the default hotkeys? Also pretty tedious imo :/ Those are 500 hks or so that i would have to go through

**Comment by Cepheid-UK** [comment]
I'll try figure out which ones it is, but really I anticipated parsing a default custom hotkeys for all the 4-digit codes that don't have a "buttonpos" field and then flagging those codes as unmovable.

**Comment by modmoto** [comment]
yes, not that hard, but we have a tree structure to represent the ui. So you would at least have to go through those to mark the ones that are not movable. IT is basically those files here:

https://github.com/w3champions/w3champions-launcher/blob/master/src/hot-keys/RaceSpecificHotkeys/hotkeyData/nightelf/units.ts

I can make the code change and implement it for gargoyle. Then Ag3nt could go through those and mark the ones that he needs as a PR?

**Comment by Cepheid-UK** [comment]
Yes if you can implement the flag once, I can add it as a PR for the ones ag3nt has found.

**Comment by modmoto** [comment]
Hey, I just pushed this feature to the branch "Hotkey-Fixes". If you want to participate there, or ask Ag3nt, should be pretty easy. To mark a Ability as not movable, replace `Ability.Create('Prioritize', 'btnairattackon', 'aatp', 'R', []),` with `Ability.Unmovable('Prioritize', 'btnairattackon', 'aatp', 'R', []),`

**Comment by modmoto** [comment]
closed with https://github.com/w3champions/w3champions-launcher/pull/47
