### ISSUE TITLE
Ability and learn ability positions are shared

### ISSUE THREAD

**Issue by abeninski** [w3champions/w3champions-launcher#46]
Ability and learn ability positions are shared. They should have different positions.

![image](https://user-images.githubusercontent.com/884808/99673875-f3883280-2a7d-11eb-80c3-e60b1263c382.png)

**Comment by modmoto** [comment]
This was actually intended, because I am lazy xD I will add it.

**Comment by modmoto** [comment]
added in https://github.com/w3champions/w3champions-launcher/pull/51
