### ISSUE TITLE
Positioning of some abilities borked

### ISSUE THREAD

**Issue by arcsaber** [w3champions/w3champions-launcher#54]
Call Militia / Back to Work positioning and hotkey seem to default when changes are being made with human (tested with changing Archmage hotkey, very mysterious). Scroll of protection doesn't move in the shop, maybe it's one of the unmoveable ones. See pic.
![bug_keys](https://user-images.githubusercontent.com/24671173/99901514-6af4d680-2cb7-11eb-9e54-2de8c75c682f.png)

Building ability seems to come without positioning

// Create Building
[cmdbuildnightelf]
Hotkey=Q

**Comment by modmoto** [comment]
what did you change in the launcher? Dont really get the picture. Top one is what was before and lower how it is now? But you did not change the location?

**Comment by arcsaber** [comment]
>what did you change in the launcher?

Archmage hotkey from W to A

>Top one is what was before and lower how it is now? But you did not change the location?

Exactly, in the 11.5 version the Call Militia position (and hotkey!) changed, now only the Back To Work position. You can test it yourself
[customkeys.txt](https://github.com/w3champions/w3champions-launcher/files/5579381/customkeys.txt)

**Comment by modmoto** [comment]
I think movein only works, if the target where you move it to, is also moved away.

The militia stuff should be fixed, in the upcoming version. We did not save the location for the additional hotkeys.

I just had a look at the HK file and it appears that everything has a custom position? You sure that there is not conflict there somehow?

**Comment by arcsaber** [comment]
> I just had a look at the HK file and it appears that everything has a custom position? You sure that there is not conflict there somehow?

Idk, I'm just amazed that changing the archmage hotkey changes the militia icon positions.

**Comment by modmoto** [comment]
you mean the build AM hotkey? Did the location change there aswell?

**Comment by modmoto** [comment]
will be fixed in https://github.com/w3champions/w3champions-launcher/pull/58
