### ISSUE TITLE
Tree of Eternity hotkey lacking

### ISSUE THREAD

**Issue by arcsaber** [w3champions/w3champions-launcher#55]
Tree of Eternity is it's own thing with [etoe]

// Upgrade to Tree of Ages/Eternity
[etoa]
Hotkey=Z
Buttonpos=0,2
UnButtonpos=0,2

**Comment by modmoto** [comment]
yes, but if you change the HK, it changes both. So it is ok? Or do you want to set Tree of ages and tree of eternity as two different hotkeys?

**Comment by arcsaber** [comment]
bug was caused my due to importing a pre 0.11.6 hotkey file
