### ISSUE TITLE
Build Structure Icon Not Repositioning

### ISSUE THREAD

**Issue by Boda805** [w3champions/w3champions-launcher#57]
Icon stays in bottom right corner even after changes made in hotkeys ui -> customkeys.txt. Across all races.

**Comment by modmoto** [comment]
Can you attach your hotkey file that is generated?

**Comment by modmoto** [comment]
I just retested it and it seams that this is a HK that can not be moved. It is correct in the file, but can not be move whatsoever. Prirotize was one example we saw aswell. Did you manage to move it somehow else? Because if not, I would mark it as not movable and disable the option in the UI.

**Comment by Boda805** [comment]
Other three races:
[cmdbuildnightelf]
Tip=(|cffffcc00Q|r) Create Building
Hotkey=Q
[AEbu]
Buttonpos=0,0

[cmdbuildhuman]
Tip=(|cffffcc00Q|r) Build Structure
Hotkey=Q
[AHbu]
Buttonpos=0,0

[cmdbuildundead]
Tip=(|cffffcc00Q|r) Summon Building
Hotkey=Q
[AUbu]
Buttonpos=0,0

**Comment by modmoto** [comment]
ah great, jeah, i will try one thing and see if this works

**Comment by modmoto** [comment]
nice, that was it. I added it in the latest release, so it might go live tonight. Thanks for the find!

**Comment by modmoto** [comment]
fixed in https://github.com/w3champions/w3champions-launcher/pull/58

**Comment by Boda805** [comment]
No problem. Oh one other small thing too for orc the build structure icon in ui is referencing 'btnhumanbuild'. I believe it should be 'btnbasicstruct'.

**Comment by modmoto** [comment]
jeah also true, i changed it for the next release
