### ISSUE TITLE
Update causing duplicate flo-worker and redownloads

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/w3champions-launcher#65]
Not sure if this is an issue with the Launcher or the Update service, but the launcher occasionally has been running an old version of flo-worker, and getting people stuck in redownload loops.

![unknown-13](https://user-images.githubusercontent.com/40397054/102559758-8db4b800-40c8-11eb-95d3-5a7c0c1b5779.png)

Could be worsened by server load during peak times?

**Comment by fluxxu** [comment]
![image](https://user-images.githubusercontent.com/4956828/102567905-78cc2a80-40b0-11eb-94d4-f12d2bac8079.png)
my bad
