### ISSUE TITLE
Flo is not running on port

### ISSUE THREAD

**Issue by Jurajzovinec** [w3champions/w3champions-launcher#67]
Flo is not running even w3c is installed with launcher and regedit Allow Local Files is set to 1.
https://w3flo.com/setup 2nd step displays mssg:
"Connection failed
Please ensure Flo is running on port 3551."

Tried to restart pc/war3/battlenet/w3c several times. Without progression.

**Comment by abeninski** [comment]
Try reading the text in the yellow box https://w3flo.com/setup
